# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
highlighter: rouge
markdown: kramdown


kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  syntax_highlighter: rouge
redcarpet:
  extensions: [fenced_code_blocks]
  render_options:
paginate: 10 # pagination based on number of posts
paginate_path: "page:num" #pagination generated sub path format
encoding: utf-8
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "yufenghe Tech Space"

description: "yufenghe Tech Space, share technology post"
author:
  name: yufenghe
  email: yufenghe87@sina.com
  github: yufenghe
  bio: Do not build on quicksand high
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: category.html
tags_path: tag.html

BASE_PATH:

exclude: ["vendor"]
gems: [jekyll-paginate]

#baidu tongji
baiduTongji:
  config: true
  id: 2159bae77d9d127b9e0caa04258dcfb2
